import type { Metadata } from "next";
import { Nunito } from "next/font/google"; // Импортируем Nunito
import "./globals.css";

// Подключение Nunito
const nunito = Nunito({
    subsets: ["latin"], // Выбор подмножества
    weight: ["400", "600", "700", "800"], // Укажите нужные веса
    variable: "--font-nunito", // Создаем CSS-переменную для шрифта
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={nunito.variable}>
        <body className="antialiased text-foreground">{children}</body>
        </html>

    );
}
