import type { Metadata } from "next";
import { Nunito } from "next/font/google"; // Импортируем Nunito
import "./globals.css";
import Footer from "@/app/components/Footer";

// Подключение Nunito
const nunito = Nunito({
    subsets: ["latin"], // Выбор подмножества
    weight: ["400", "600", "700", "800"], // Укажите нужные веса
    variable: "--font-nunito", // Создаем CSS-переменную для шрифта
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={nunito.variable}>
        <body className="antialiased text-foreground flex flex-col min-h-screen">
        {/* Контейнер с ограниченной шириной */}
        <div className="max-w-[1350px] w-full mx-auto  flex-1">
            <main className="flex-1">{children}</main>
            <Footer /> {/* Футер остаётся прижатым к низу */}
        </div>
        </body>
        </html>
    );
}
